# Generated by Django 2.2.12 on 2020-04-17 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_sshconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='token',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
